### ISSUE TITLE
NullPointer when using asPublish and the service method hasn't an argument.

### ISSUE THREAD

**Issue by rapatao** [rapatao/vertx-eventbus-proxyhelper-java#1]
NullPointer when using asPublish and the service method hasn't an argument.

```
SEVERE: Unhandled exception
java.lang.NullPointerException
	at java.util.Arrays.stream(Arrays.java:5004)
	at com.rapatao.vertx.eventbus.proxyhelper.EventBusPublishInvocationHandler.invoke(EventBusPublishInvocationHandler.java:25)
	at com.sun.proxy.$Proxy4.check(Unknown Source)
	at com.rapatao.tests.worker.RunnerTest.lambda$null$1(RunnerTest.java:60)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:782)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:753)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rapatao** [comment]
Fixed in version 0.0.4-RELEASE
